export const PROJECT_ID = "golfer-goodies-local";
export const PASSWORD = "LocalGoodies22!";
export const users = [
  "golfer",
  "owner",
  "manager",
  "staff",
  "runner",
  "suspended",
  "support",
  "platform-admin",
].map((name, index) => ({
  uid: `local-${name}`,
  email: `${name}@example.com`,
  displayName: `Fictional ${name.replace("-", " ")}`,
  fixtureRole: name,
  index,
}));
const templates = [
  [
    "summit-pines",
    "Summit Pines Resort",
    "Silver Hollow",
    "CO",
    "America/Denver",
    "Premium resort-style course",
    ["Spa pavilion", "Mountain practice range"],
    ["pickup", "cart-delivery"],
    1500,
    18,
    "active",
    true,
  ],
  [
    "meadow-loop",
    "Meadow Loop Public Golf",
    "Kindred",
    "OH",
    "America/New_York",
    "Friendly public course",
    ["Family tees", "Community range"],
    ["pickup", "on-course-meetup"],
    500,
    15,
    "active",
    true,
  ],
  [
    "circuit-links",
    "Circuit Links",
    "Nova City",
    "TX",
    "America/Chicago",
    "Technology-forward urban course",
    ["Smart lockers", "Night range"],
    ["pickup", "cart-delivery", "on-course-meetup"],
    1000,
    12,
    "active",
    true,
  ],
  [
    "heritage-oaks",
    "Heritage Oaks Club",
    "Oldbridge",
    "VA",
    "America/New_York",
    "Traditional private club",
    ["Caddie house", "Heritage library"],
    ["pickup"],
    2000,
    25,
    "paused",
    false,
  ],
  [
    "cedar-bend-muni",
    "Cedar Bend Municipal",
    "Fairview",
    "KS",
    "America/Chicago",
    "Affordable municipal course",
    ["Youth practice green", "Public pavilion"],
    ["pickup"],
    0,
    10,
    "active",
    true,
  ],
];
export const categoryTemplates = [
  ["at-turn", "At the Turn"],
  ["quick-snacks", "Quick Snacks"],
  ["cold-drinks", "Cold Drinks"],
  ["sandwiches-wraps", "Sandwiches and Wraps"],
  ["golf-essentials", "Golf Essentials"],
  ["weather-rescue", "Weather Rescue"],
  ["personal-care", "Personal-Care Essentials"],
  ["course-experiences", "Course Experiences"],
];
const products = [
  ["Turn Box", 925],
  ["Roasted Trail Mix", 475],
  ["Citrus Sparkler", 350],
  ["Garden Club Wrap", 1175],
  ["Fictional Ball Sleeve", 825],
  ["Pocket Rain Poncho", 695],
  ["Mineral Sunscreen", 795],
  ["Practice Green Token", 500],
];
export const courses = templates.map((t, index) => ({
  id: t[0],
  slug: t[0],
  name: t[1],
  shortDescription: `A fictional ${String(t[5]).toLowerCase()} marketplace.`,
  city: t[2],
  state: t[3],
  timezone: t[4],
  archetype: t[5],
  status: t[10],
  verified: index < 3,
  featured: index === 0,
  marketplaceVisible: t[11],
  acceptsOrders: index !== 3,
  fulfillmentMethods: t[7],
  minimumOrderCents: t[8],
  defaultPrepMinutes: t[9],
  amenities: t[6],
  imagePaths: [],
  categories: categoryTemplates.map(([id, name]) => ({
    id,
    name,
    sortOrder: categoryTemplates.findIndex((c) => c[0] === id),
  })),
  products: products.map(([name, price], i) => ({
    id: `${t[0]}-${categoryTemplates[i][0]}`,
    courseId: t[0],
    categoryId: categoryTemplates[i][0],
    name,
    shortDescription: `Fictional ${String(name).toLowerCase()} for local testing.`,
    priceCents: Number(price) + index * 50,
    currency: "usd",
    tags: ["fictional", "alcohol-free"],
    preparationMinutes: Number(t[9]) + (i % 3),
    status: i === 7 && index === 2 ? "unavailable" : "active",
    featured: i < 2,
    inventoryMode: i === 4 ? "tracked" : "unlimited",
    ...(i === 4 ? { quantityAvailable: 24 } : {}),
  })),
  promotion: {
    id: `${t[0]}-welcome`,
    title: "Fictional welcome offer",
    active: index !== 3,
    public: true,
  },
}));
